import { Game } from "./supabase/types"

export const SEED_GAMES: Omit<Game, "id" | "created_at" | "user_id">[] = [
  {
    title: "The Legend of Zelda: Breath of the Wild",
    console: "Nintendo Switch",
    status: "completed",
    days_played: 45,
    start_date: "2023-01-10",
    end_date: "2023-02-24",
    rating: 10,
    notes: "Masterpiece. Explored every corner of Hyrule.",
    cover_url: null,
  },
  {
    title: "God of War Ragnarök",
    console: "PlayStation 5",
    status: "completed",
    days_played: 30,
    start_date: "2023-03-01",
    end_date: "2023-03-31",
    rating: 9,
    notes: "Epic story, incredible graphics.",
    cover_url: null,
  },
  {
    title: "Elden Ring",
    console: "PC",
    status: "playing",
    days_played: 60,
    start_date: "2023-04-15",
    end_date: null,
    rating: null,
    notes: "Still exploring the Lands Between.",
    cover_url: null,
  },
  {
    title: "Hollow Knight",
    console: "Nintendo Switch",
    status: "dropped",
    days_played: 10,
    start_date: "2022-12-01",
    end_date: "2022-12-11",
    rating: 7,
    notes: "Great game but got too busy.",
    cover_url: null,
  },
  {
    title: "Cyberpunk 2077",
    console: "PC",
    status: "backlog",
    days_played: null,
    start_date: null,
    end_date: null,
    rating: null,
    notes: "Heard the post-patch version is amazing.",
    cover_url: null,
  },
]
